server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_provider?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: 1234
  application:
    name: microservice-provider-user

logging:
  level:
    root : INFO

info:
  app:
      java:
         source:@java.version@
         target:@java.version@
      encoding: "UTF-8"
  developer: chenzhuo
  lover: huangjing

eureka:
  client:
    eureka-server-u-r-l-context:  http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
        my-metadata : 用户端-自定义数据
        otherData : user-part